### ISSUE TITLE
Support for as-is page names

### ISSUE THREAD

**Issue by laurencer** [laurencer/confluence-sync#2]
Currently page names are automatically title cased based on a few rules: `my-file-name.md` becomes `My File Name` as a page. This is nice for the common case but can make a few pages look extremely messy, especially where there is an acronym: `ABC Learning` becoming `Abc Learning`.

**It would be fantastic if the user could specify whether to preserve the original casing of a file name.**

One way to approach this is to embed this in-band. My current thinking is that appending a `.` at the end of the file or directory name could be used to disable any case modifications. For example `ABC-Learning..md` would become `ABC Learning`, and a folder named `ATMs.` would become `ATMs`.

**Comment by laurencer** [comment]
\cc @pdericson - any thoughts on this, not sure if you've come across this problem?

**Comment by pdericson** [comment]
How about splitting on hyphen and only capitalising the words that do not contain any upper case characters?

**Comment by laurencer** [comment]
Good idea - might implement that as an initial stop gap (behind a feature flag).

**Comment by laurencer** [comment]
Implemented in master behind a feature flag.
